version: 2.1

workflows:
  version: 2
  tests-workflow:
    jobs:
      - build
      - test-version:
          version: "3.6"
          requires:
            - build
      - test-version:
          version: "3.7"
          requires:
            - build
      - test-version:
          version: "2.7"
          requires:
            - build

  deployment-workflow:
    jobs:
      # Runs build and test, but now just on Git tags (created from a GitHub release)
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - test-version:
          version: "3.6"
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      # Runs the deployment job, just with the tags as well
      - deployment:
          requires:
            - test-version
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/

workflows:
  version: 2

  tests-workflow:
    jobs:
      - build
      - test-version:
          version: "3.6"
          requires:
            - build
      - test-version:
          version: "3.7"
          requires:
            - build
      - test-version:
          version: "2.7"
          requires:
            - build

  deployment-workflow:
    jobs:
      # Runs build and test, but now just on Git tags (created from a GitHub release)
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - test-version:
          version: "3.6"
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      # Runs the deployment job, just with the tags as well
      - deployment:
          requires:
            - test-version
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Linting
          command: |
            poetry run pre-commit run --source origin/master --origin HEAD

  test-version:
    parameters:
      version:
        type: string
        default: "3.6.8"
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Tests
          command: |
            poetry run true

  deploy:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction
